---
- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart sshd

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd

- name: Set SSH idle timeout
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: 'ClientAliveInterval 300'
    state: present
  notify: Restart sshd

- name: Install nftables
  ansible.builtin.dnf:
    name: nftables
    state: present

- name: Enable and start nftables
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true
